### ISSUE TITLE
Stripping 'r' instead of '\r'.

### ISSUE THREAD

**Issue by SamuelMcGowan** [nomad/crop#12]
I'm making a text editor, and noticed 'r's are removed from the end of lines when iterating over them with the `Lines` iterator. I had a look in the `crop` codebase and found this suspicious looking line:
https://github.com/nomad/crop/blob/b6cde93deacc26ea8f7062418b7bbfe5cc6e9790/src/rope/gap_slice.rs#L154

**Comment by noib3** [comment]
Thanks for finding this, I fixed it in https://github.com/nomad/crop/commit/f520217b4d71372040dcb2ea2fa9af7247bd14fc and released a new minor version that includes the fix.
