### ISSUE TITLE
[BUG]: Weird utf16 index conversion when `ñ` is present, tested on crop@0.4.2

### ISSUE THREAD

**Issue by criloz** [nomad/crop#22]
**version**: crop@0.4.2

## description 
The index conversion from `bytes` to `utf-16` are being miscalculated when symbols like `ñ` or `¶` are present in the rope, there not being counting even though they only take one ut16 code point;

### with `ñ`

here `utf16_code_unit_of_byte` should return `4` but is returns `3`

```rust
let s = r#"xñz | ####"#;
let r = Rope::from(s);
println!("{:?}", r.utf16_code_unit_of_byte(4))// should return `4` but returns `3`
```

### with `n`

working as expected

```rust
let s = r#"xnz | ####"#;
let r = Rope::from(s);
println!("{:?}", r.utf16_code_unit_of_byte(4))//  returns 4 correclty
```

**Comment by noib3** [comment]
I believe the current behaviour is correct. `ñ` takes up 2 bytes when encoded in UTF-8, so a byte offset of 4 in `xñz | ####` gets you `xñz`, which takes up 3 UTF-16 code units.

**Comment by criloz** [comment]
@noib3 thanks for the fast response and for the library, indeed the crop just works fine,  I was doing a terrible mistake in a parsing, and I was getting weird conversion of indices from wasm to JavaScript
